name: Destroy Infrastructure

on:
  workflow_dispatch:  # allows manual triggering via GitHub UI

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: ./terraform  # adjust if your Terraform files are elsewhere

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: boris7803/pf_infra
          token: ${{ secrets.PF_TOKEN }}
          path: pf_infra


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
